# Generated by Django 5.0.4 on 2024-05-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_parent_id', models.IntegerField(blank=True, null=True)),
                ('cate_name', models.TextField(blank=True, null=True)),
                ('cate_description', models.TextField(blank=True, null=True)),
                ('cate_status', models.BooleanField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(blank=True, null=True)),
                ('ship_name', models.TextField(blank=True, null=True)),
                ('ship_address', models.TextField(blank=True, null=True)),
                ('ship_phone', models.TextField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.TextField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('diachi', models.TextField(blank=True, null=True)),
                ('huyen', models.TextField(blank=True, null=True)),
                ('tinh', models.TextField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_price_new', models.IntegerField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_detail', models.TextField(blank=True, null=True)),
                ('product_status', models.BooleanField(blank=True, null=True)),
                ('rate', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
