# Generated by Django 5.0.4 on 2024-05-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderdetail_address_orderdetail_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
